version: "2.1"
services:
  yelb-ui:
    build: ../../yelb-ui
    depends_on:
      - yelb-appserver
    ports:
      - 8080:80
    environment:
      - UI_ENV=dev # dev | test | prod 

  yelb-appserver:
    build: ../../yelb-appserver
    depends_on:
      - redis-server
      - yelb-db
    ports:
      - 4567:4567
    environment:
      - RACK_ENV=development # development | test | production 

  redis-server:
    image: redis:4.0.2
    ports:
      - 6379:6379

  yelb-db:
    build: ../../yelb-db
    ports:
      - 5432:5432
