version: "2.1"
services:
  yelb-ui:
    build: ../../yelb-ui
    depends_on:
      - yelb-phoenix
    ports:
      - 8080:80
    environment:
      - UI_ENV=dev # dev | test | prod 

  yelb-phoenix:
    build: ../../yelb-phoenix
    depends_on:
      - redis-server
    ports:
      - 4000:4000
    environment:
      - HOST=localhost
      - SECRET_KEY_BASE=SUPERSECRET!
      - POD_IP=127.0.0.1
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

  redis-server:
    build: ../../redis-server
    ports:
      - 6379:6379
