# This should work on Kubernetes deployments that have LoadBalancer support
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
    tier: db
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis-server
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-phoenix
  labels:
    app: yelb-phoenix
    tier: middletier
spec:
  type: ClusterIP
  ports:
    - port: 4000
  selector:
    app: yelb-phoenix
    tier: middletier
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-phoenix-headless
  labels:
    app: yelb-phoenix-headless
spec:
  clusterIP: None
  ports:
    - port: 4000
  selector:
    app: yelb-phoenix
    tier: middletier
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: yelb-ui
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
        - name: yelb-ui
          image: fauh45/yelb-ui:v1.2.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "0.8"
              memory: 1Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-ui
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
      tier: db
  template:
    metadata:
      labels:
        app: redis-server
        tier: db
    spec:
      containers:
        - name: redis-server
          image: fauh45/yelb-redis-server:v0.1.0
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-phoenix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-phoenix
      tier: middletier
  template:
    metadata:
      labels:
        app: yelb-phoenix
        tier: middletier
    spec:
      containers:
        - name: yelb-phoenix
          image: fauh45/yelb-phoenix:v0.1.0
          ports:
            - containerPort: 4567
          env:
            - name: HOST
              value: yelb-ui-fauh45.cloud.okteto.net
            - name: SECRET_KEY_BASE
              value: CBqIGdHTlIBn5a5D7cdF4dCWifQVaQSI3lXZLzOy
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 2Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-phoenix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-phoenix
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
